export default {
  segment: 64,
  headUp: {x: 3, y: 0},
  headRight: {x: 4, y: 0},
  headDown: {x: 4, y: 1},
  headLeft: {x: 3, y: 1},
  tailUp: {x: 3, y: 2},
  tailRight: {x: 4, y: 2},
  tailDown: {x: 4, y: 3},
  tailLeft: {x: 3, y: 3},
  bodyHorizontal: {x: 1, y: 0},
  bodyVertical: {x: 2, y:1},
  bodyAngleLefDown: {x: 2, y: 0},
  bodyAngleLeftUp: {x: 0, y: 1},
  bodyAngleLeftDown: {x: 0, y: 0},
  bodyAngleDownLeft: {x: 2, y: 2},
  bodyAngleDownRight: {x: 0, y: 1},
  bodyAngleRightDown: {x: 2, y: 0},
  bodyAngleRightUp: {x: 2, y: 2},
  bodyAngleUpRight: {x: 0, y: 0},
  bodyAngleUpLeft: {x: 2, y: 0},
}